//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.transaction;

import com.keybridgeglobal.wsif.enumerated.EnumWsifWsdMode;
import com.keybridgeglobal.wsif.entity.Schedule;
import com.keybridgeglobal.wsif.entity.Channel;
import com.keybridgeglobal.wsif.entity.Location;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for whitespaceFrequency complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="whitespaceFrequency">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wsdModeList" type="{}enumWsifWsdMode" maxOccurs="unbounded"/>
 *         &lt;element ref="{}channel"/>
 *         &lt;element ref="{}location"/>
 *         &lt;element ref="{}schedule"/>
 *         &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="erpMax" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "whitespaceFrequency", propOrder = {
    "wsdModeList",
    "channel",
    "location",
    "schedule",
    "extension"
})
public class WhitespaceFrequency {

    @XmlElement(required = true)
    protected List<EnumWsifWsdMode> wsdModeList;
    @XmlElement(required = true)
    protected Channel channel;
    @XmlElement(required = true)
    protected Location location;
    @XmlElement(required = true)
    protected Schedule schedule;
    protected String extension;
    @XmlAttribute(name = "uuid", required = true)
    protected String uuid;
    @XmlAttribute(name = "erpMax")
    protected Double erpMax;

    /**
     * Gets the value of the wsdModeList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wsdModeList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWsdModeList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnumWsifWsdMode }
     *
     *
     */
    public List<EnumWsifWsdMode> getWsdModeList() {
        if (wsdModeList == null) {
            wsdModeList = new ArrayList<EnumWsifWsdMode>();
        }
        return this.wsdModeList;
    }

    /**
     * Gets the value of the channel property.
     *
     * @return
     *     possible object is
     *     {@link Channel }
     *
     */
    public Channel getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     *
     * @param value
     *     allowed object is
     *     {@link Channel }
     *
     */
    public void setChannel(Channel value) {
        this.channel = value;
    }

    /**
     * Gets the value of the location property.
     *
     * @return
     *     possible object is
     *     {@link Location }
     *
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     *
     * @param value
     *     allowed object is
     *     {@link Location }
     *
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the schedule property.
     *
     * @return
     *     possible object is
     *     {@link Schedule }
     *
     */
    public Schedule getSchedule() {
        return schedule;
    }

    /**
     * Sets the value of the schedule property.
     *
     * @param value
     *     allowed object is
     *     {@link Schedule }
     *
     */
    public void setSchedule(Schedule value) {
        this.schedule = value;
    }

    /**
     * Gets the value of the extension property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExtension(String value) {
        this.extension = value;
    }

    /**
     * Gets the value of the uuid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the erpMax property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getErpMax() {
        return erpMax;
    }

    /**
     * Sets the value of the erpMax property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setErpMax(Double value) {
        this.erpMax = value;
    }

}
