//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//
package com.keybridgeglobal.wsif;

import com.keybridgeglobal.wsif.entity.*;
import com.keybridgeglobal.wsif.entity.device.*;
import com.keybridgeglobal.wsif.entity.enumerated.*;
import com.keybridgeglobal.wsif.transaction.WhitespaceFrequency;
import com.keybridgeglobal.wsif.transaction.WhitespaceQuery;
import com.keybridgeglobal.wsif.transaction.WhitespaceResponse;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p/>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _RxLpaux_QNAME = new QName("", "rxLpaux");
  private final static QName _TxRxLandMobileBase_QNAME = new QName("", "txRxLandMobileBase");
  private final static QName _Location_QNAME = new QName("", "location");
  private final static QName _WhitespaceRegistration_QNAME = new QName("", "whitespaceRegistration");
  private final static QName _WhitespaceResponse_QNAME = new QName("", "whitespaceResponse");
  private final static QName _RxTv_QNAME = new QName("", "rxTv");
  private final static QName _Contact_QNAME = new QName("", "contact");
  private final static QName _EnumWaiverTvrx_QNAME = new QName("", "enumWaiverTvrx");
  private final static QName _RxGeneric_QNAME = new QName("", "rxGeneric");
  private final static QName _TxGeneric_QNAME = new QName("", "txGeneric");
  private final static QName _TxMicrowave_QNAME = new QName("", "txMicrowave");
  private final static QName _WirelessService_QNAME = new QName("", "wirelessService");
  private final static QName _WhitespaceQuery_QNAME = new QName("", "whitespaceQuery");
  private final static QName _EnumRadioAstronomy_QNAME = new QName("", "enumRadioAstronomy");
  private final static QName _License_QNAME = new QName("", "license");
  private final static QName _EnumWaiverMvpd_QNAME = new QName("", "enumWaiverMvpd");
  private final static QName _TxLpaux_QNAME = new QName("", "txLpaux");
  private final static QName _Coordinate_QNAME = new QName("", "coordinate");
  private final static QName _Station_QNAME = new QName("", "station");
  private final static QName _EnumOffshoreRadio_QNAME = new QName("", "enumOffshoreRadio");
  private final static QName _Antenna_QNAME = new QName("", "antenna");
  private final static QName _RxMicrowave_QNAME = new QName("", "rxMicrowave");
  private final static QName _EnumWaiverTvrxPK_QNAME = new QName("", "enumWaiverTvrxPK");
  private final static QName _Geometry_QNAME = new QName("", "geometry");
  private final static QName _TxTv_QNAME = new QName("", "txTv");
  private final static QName _WhitespaceFrequency_QNAME = new QName("", "whitespaceFrequency");
  private final static QName _Schedule_QNAME = new QName("", "schedule");
  private final static QName _EnumUrban_QNAME = new QName("", "enumUrban");
  private final static QName _TxRxWsd_QNAME = new QName("", "txRxWsd");
  private final static QName _Address_QNAME = new QName("", "address");
  private final static QName _Device_QNAME = new QName("", "device");
  private final static QName _TxRxLandMobile_QNAME = new QName("", "txRxLandMobile");
  private final static QName _Channel_QNAME = new QName("", "channel");

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package: generated
   * <p/>
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link RxLpaux }
   *
   */
  public RxLpaux createRxLpaux() {
    return new RxLpaux();
  }

  /**
   * Create an instance of {@link TxRxLandMobileBase }
   *
   */
  public TxRxLandMobileBase createTxRxLandMobileBase() {
    return new TxRxLandMobileBase();
  }

  /**
   * Create an instance of {@link WhitespaceRegistration }
   *
   */
  public WhitespaceRegistration createWhitespaceRegistration() {
    return new WhitespaceRegistration();
  }

  /**
   * Create an instance of {@link Location }
   *
   */
  public Location createLocation() {
    return new Location();
  }

  /**
   * Create an instance of {@link WhitespaceResponse }
   *
   */
  public WhitespaceResponse createWhitespaceResponse() {
    return new WhitespaceResponse();
  }

  /**
   * Create an instance of {@link RxTv }
   *
   */
  public RxTv createRxTv() {
    return new RxTv();
  }

  /**
   * Create an instance of {@link EnumWaiverTvrx }
   *
   */
  public EnumWaiverTvrx createEnumWaiverTvrx() {
    return new EnumWaiverTvrx();
  }

  /**
   * Create an instance of {@link Contact }
   *
   */
  public Contact createContact() {
    return new Contact();
  }

  /**
   * Create an instance of {@link RxGeneric }
   *
   */
  public RxGeneric createRxGeneric() {
    return new RxGeneric();
  }

  /**
   * Create an instance of {@link TxGeneric }
   *
   */
  public TxGeneric createTxGeneric() {
    return new TxGeneric();
  }

  /**
   * Create an instance of {@link TxMicrowave }
   *
   */
  public TxMicrowave createTxMicrowave() {
    return new TxMicrowave();
  }

  /**
   * Create an instance of {@link WirelessService }
   *
   */
  public WirelessService createWirelessService() {
    return new WirelessService();
  }

  /**
   * Create an instance of {@link WhitespaceQuery }
   *
   */
  public WhitespaceQuery createWhitespaceQuery() {
    return new WhitespaceQuery();
  }

  /**
   * Create an instance of {@link EnumRadioAstronomy }
   *
   */
  public EnumRadioAstronomy createEnumRadioAstronomy() {
    return new EnumRadioAstronomy();
  }

  /**
   * Create an instance of {@link License }
   *
   */
  public License createLicense() {
    return new License();
  }

  /**
   * Create an instance of {@link EnumWaiverMvpd }
   *
   */
  public EnumWaiverMvpd createEnumWaiverMvpd() {
    return new EnumWaiverMvpd();
  }

  /**
   * Create an instance of {@link TxLpaux }
   *
   */
  public TxLpaux createTxLpaux() {
    return new TxLpaux();
  }

  /**
   * Create an instance of {@link Coordinate }
   *
   */
  public Coordinate createCoordinate() {
    return new Coordinate();
  }

  /**
   * Create an instance of {@link Station }
   *
   */
  public Station createStation() {
    return new Station();
  }

  /**
   * Create an instance of {@link EnumOffshoreRadio }
   *
   */
  public EnumOffshoreRadio createEnumOffshoreRadio() {
    return new EnumOffshoreRadio();
  }

  /**
   * Create an instance of {@link Antenna }
   *
   */
  public Antenna createAntenna() {
    return new Antenna();
  }

  /**
   * Create an instance of {@link RxMicrowave }
   *
   */
  public RxMicrowave createRxMicrowave() {
    return new RxMicrowave();
  }

  /**
   * Create an instance of {@link EnumWaiverTvrxPK }
   *
   */
  public EnumWaiverTvrxPK createEnumWaiverTvrxPK() {
    return new EnumWaiverTvrxPK();
  }

  /**
   * Create an instance of {@link TxTv }
   *
   */
  public TxTv createTxTv() {
    return new TxTv();
  }

  /**
   * Create an instance of {@link Geometry }
   *
   */
  public Geometry createGeometry() {
    return new Geometry();
  }

  /**
   * Create an instance of {@link WhitespaceFrequency }
   *
   */
  public WhitespaceFrequency createWhitespaceFrequency() {
    return new WhitespaceFrequency();
  }

  /**
   * Create an instance of {@link Schedule }
   *
   */
  public Schedule createSchedule() {
    return new Schedule();
  }

  /**
   * Create an instance of {@link EnumUrban }
   *
   */
  public EnumUrban createEnumUrban() {
    return new EnumUrban();
  }

  /**
   * Create an instance of {@link TxRxWsd }
   *
   */
  public TxRxWsd createTxRxWsd() {
    return new TxRxWsd();
  }

  /**
   * Create an instance of {@link Address }
   *
   */
  public Address createAddress() {
    return new Address();
  }

  /**
   * Create an instance of {@link TxRxLandMobile }
   *
   */
  public TxRxLandMobile createTxRxLandMobile() {
    return new TxRxLandMobile();
  }

  /**
   * Create an instance of {@link Channel }
   *
   */
  public Channel createChannel() {
    return new Channel();
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link RxLpaux }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "rxLpaux")
  public JAXBElement<RxLpaux> createRxLpaux(RxLpaux value) {
    return new JAXBElement<RxLpaux>(_RxLpaux_QNAME, RxLpaux.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link TxRxLandMobileBase }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "txRxLandMobileBase")
  public JAXBElement<TxRxLandMobileBase> createTxRxLandMobileBase(TxRxLandMobileBase value) {
    return new JAXBElement<TxRxLandMobileBase>(_TxRxLandMobileBase_QNAME, TxRxLandMobileBase.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link Location }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "location")
  public JAXBElement<Location> createLocation(Location value) {
    return new JAXBElement<Location>(_Location_QNAME, Location.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link WhitespaceRegistration }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "whitespaceRegistration")
  public JAXBElement<WhitespaceRegistration> createWhitespaceRegistration(WhitespaceRegistration value) {
    return new JAXBElement<WhitespaceRegistration>(_WhitespaceRegistration_QNAME, WhitespaceRegistration.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link WhitespaceResponse }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "whitespaceResponse")
  public JAXBElement<WhitespaceResponse> createWhitespaceResponse(WhitespaceResponse value) {
    return new JAXBElement<WhitespaceResponse>(_WhitespaceResponse_QNAME, WhitespaceResponse.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link RxTv }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "rxTv")
  public JAXBElement<RxTv> createRxTv(RxTv value) {
    return new JAXBElement<RxTv>(_RxTv_QNAME, RxTv.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link Contact }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "contact")
  public JAXBElement<Contact> createContact(Contact value) {
    return new JAXBElement<Contact>(_Contact_QNAME, Contact.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link EnumWaiverTvrx }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "enumWaiverTvrx")
  public JAXBElement<EnumWaiverTvrx> createEnumWaiverTvrx(EnumWaiverTvrx value) {
    return new JAXBElement<EnumWaiverTvrx>(_EnumWaiverTvrx_QNAME, EnumWaiverTvrx.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link RxGeneric }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "rxGeneric")
  public JAXBElement<RxGeneric> createRxGeneric(RxGeneric value) {
    return new JAXBElement<RxGeneric>(_RxGeneric_QNAME, RxGeneric.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link TxGeneric }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "txGeneric")
  public JAXBElement<TxGeneric> createTxGeneric(TxGeneric value) {
    return new JAXBElement<TxGeneric>(_TxGeneric_QNAME, TxGeneric.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link TxMicrowave }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "txMicrowave")
  public JAXBElement<TxMicrowave> createTxMicrowave(TxMicrowave value) {
    return new JAXBElement<TxMicrowave>(_TxMicrowave_QNAME, TxMicrowave.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link WirelessService }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "wirelessService")
  public JAXBElement<WirelessService> createWirelessService(WirelessService value) {
    return new JAXBElement<WirelessService>(_WirelessService_QNAME, WirelessService.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link WhitespaceQuery }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "whitespaceQuery")
  public JAXBElement<WhitespaceQuery> createWhitespaceQuery(WhitespaceQuery value) {
    return new JAXBElement<WhitespaceQuery>(_WhitespaceQuery_QNAME, WhitespaceQuery.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link EnumRadioAstronomy }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "enumRadioAstronomy")
  public JAXBElement<EnumRadioAstronomy> createEnumRadioAstronomy(EnumRadioAstronomy value) {
    return new JAXBElement<EnumRadioAstronomy>(_EnumRadioAstronomy_QNAME, EnumRadioAstronomy.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link License }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "license")
  public JAXBElement<License> createLicense(License value) {
    return new JAXBElement<License>(_License_QNAME, License.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link EnumWaiverMvpd }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "enumWaiverMvpd")
  public JAXBElement<EnumWaiverMvpd> createEnumWaiverMvpd(EnumWaiverMvpd value) {
    return new JAXBElement<EnumWaiverMvpd>(_EnumWaiverMvpd_QNAME, EnumWaiverMvpd.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link TxLpaux }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "txLpaux")
  public JAXBElement<TxLpaux> createTxLpaux(TxLpaux value) {
    return new JAXBElement<TxLpaux>(_TxLpaux_QNAME, TxLpaux.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link Coordinate }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "coordinate")
  public JAXBElement<Coordinate> createCoordinate(Coordinate value) {
    return new JAXBElement<Coordinate>(_Coordinate_QNAME, Coordinate.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link Station }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "station")
  public JAXBElement<Station> createStation(Station value) {
    return new JAXBElement<Station>(_Station_QNAME, Station.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link EnumOffshoreRadio }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "enumOffshoreRadio")
  public JAXBElement<EnumOffshoreRadio> createEnumOffshoreRadio(EnumOffshoreRadio value) {
    return new JAXBElement<EnumOffshoreRadio>(_EnumOffshoreRadio_QNAME, EnumOffshoreRadio.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link Antenna }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "antenna")
  public JAXBElement<Antenna> createAntenna(Antenna value) {
    return new JAXBElement<Antenna>(_Antenna_QNAME, Antenna.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link RxMicrowave }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "rxMicrowave")
  public JAXBElement<RxMicrowave> createRxMicrowave(RxMicrowave value) {
    return new JAXBElement<RxMicrowave>(_RxMicrowave_QNAME, RxMicrowave.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link EnumWaiverTvrxPK }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "enumWaiverTvrxPK")
  public JAXBElement<EnumWaiverTvrxPK> createEnumWaiverTvrxPK(EnumWaiverTvrxPK value) {
    return new JAXBElement<EnumWaiverTvrxPK>(_EnumWaiverTvrxPK_QNAME, EnumWaiverTvrxPK.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link Geometry }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "geometry")
  public JAXBElement<Geometry> createGeometry(Geometry value) {
    return new JAXBElement<Geometry>(_Geometry_QNAME, Geometry.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link TxTv }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "txTv")
  public JAXBElement<TxTv> createTxTv(TxTv value) {
    return new JAXBElement<TxTv>(_TxTv_QNAME, TxTv.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link WhitespaceFrequency }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "whitespaceFrequency")
  public JAXBElement<WhitespaceFrequency> createWhitespaceFrequency(WhitespaceFrequency value) {
    return new JAXBElement<WhitespaceFrequency>(_WhitespaceFrequency_QNAME, WhitespaceFrequency.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link Schedule }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "schedule")
  public JAXBElement<Schedule> createSchedule(Schedule value) {
    return new JAXBElement<Schedule>(_Schedule_QNAME, Schedule.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link EnumUrban }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "enumUrban")
  public JAXBElement<EnumUrban> createEnumUrban(EnumUrban value) {
    return new JAXBElement<EnumUrban>(_EnumUrban_QNAME, EnumUrban.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link TxRxWsd }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "txRxWsd")
  public JAXBElement<TxRxWsd> createTxRxWsd(TxRxWsd value) {
    return new JAXBElement<TxRxWsd>(_TxRxWsd_QNAME, TxRxWsd.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link Address }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "address")
  public JAXBElement<Address> createAddress(Address value) {
    return new JAXBElement<Address>(_Address_QNAME, Address.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link Device }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "device")
  public JAXBElement<Device> createDevice(Device value) {
    return new JAXBElement<Device>(_Device_QNAME, Device.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link TxRxLandMobile }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "txRxLandMobile")
  public JAXBElement<TxRxLandMobile> createTxRxLandMobile(TxRxLandMobile value) {
    return new JAXBElement<TxRxLandMobile>(_TxRxLandMobile_QNAME, TxRxLandMobile.class, null, value);
  }

  /**
   * Create an instance of
   * {@link JAXBElement }{@code <}{@link Channel }{@code >}}
   * <p/>
   */
  @XmlElementDecl(namespace = "", name = "channel")
  public JAXBElement<Channel> createChannel(Channel value) {
    return new JAXBElement<Channel>(_Channel_QNAME, Channel.class, null, value);
  }
}
