//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.enumerated;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumWsifWhitespaceType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumWsifWhitespaceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="KEYBRIDGE_DEMO"/>
 *     &lt;enumeration value="GOV_FCC_WHITESPACETYPE_ASTR"/>
 *     &lt;enumeration value="GOV_FCC_WHITESPACETYPE_ORS"/>
 *     &lt;enumeration value="GOV_FCC_WHITESPACETYPE_URBAN"/>
 *     &lt;enumeration value="GOV_FCC_WHITESPACETYPE_LMRS"/>
 *     &lt;enumeration value="GOV_FCC_WHITESPACETYPE_LPAUX"/>
 *     &lt;enumeration value="GOV_FCC_WHITESPACETYPE_TV"/>
 *     &lt;enumeration value="GOV_FCC_WHITESPACETYPE_TV_RX"/>
 *     &lt;enumeration value="GOV_FCC_WHITESPACETYPE_TV_DD"/>
 *     &lt;enumeration value="GOV_FCC_WHITESPACETYPE_BCAUX"/>
 *     &lt;enumeration value="GOV_FCC_WHITESPACETYPE_TV_RX_MVPD"/>
 *     &lt;enumeration value="CA_GC_IC_WHITESPACETYPE_TV"/>
 *     &lt;enumeration value="CA_GC_IC_WHITESPACETYPE_TV_RX"/>
 *     &lt;enumeration value="MX_GOV_COFETEL_WHITESPACETYPE_TV"/>
 *     &lt;enumeration value="MX_GOV_COFETEL_WHITESPACETYPE_TV_RX"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "enumWsifWhitespaceType")
@XmlEnum
public enum EnumWsifWhitespaceType {

    KEYBRIDGE_DEMO,
    GOV_FCC_WHITESPACETYPE_ASTR,
    GOV_FCC_WHITESPACETYPE_ORS,
    GOV_FCC_WHITESPACETYPE_URBAN,
    GOV_FCC_WHITESPACETYPE_LMRS,
    GOV_FCC_WHITESPACETYPE_LPAUX,
    GOV_FCC_WHITESPACETYPE_TV,
    GOV_FCC_WHITESPACETYPE_TV_RX,
    GOV_FCC_WHITESPACETYPE_TV_DD,
    GOV_FCC_WHITESPACETYPE_BCAUX,
    GOV_FCC_WHITESPACETYPE_TV_RX_MVPD,
    CA_GC_IC_WHITESPACETYPE_TV,
    CA_GC_IC_WHITESPACETYPE_TV_RX,
    MX_GOV_COFETEL_WHITESPACETYPE_TV,
    MX_GOV_COFETEL_WHITESPACETYPE_TV_RX;

    public String value() {
        return name();
    }

    public static EnumWsifWhitespaceType fromValue(String v) {
        return valueOf(v);
    }

}
