//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.enumerated;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumWsifDataSource.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumWsifDataSource">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="KEYBRIDGE"/>
 *     &lt;enumeration value="ENUMERATED"/>
 *     &lt;enumeration value="CDBS"/>
 *     &lt;enumeration value="COALS"/>
 *     &lt;enumeration value="ELS"/>
 *     &lt;enumeration value="IBFS"/>
 *     &lt;enumeration value="LICENSE"/>
 *     &lt;enumeration value="ULS"/>
 *     &lt;enumeration value="BDBS"/>
 *     &lt;enumeration value="COFETEL"/>
 *     &lt;enumeration value="PEERING"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "enumWsifDataSource")
@XmlEnum
public enum EnumWsifDataSource {

    KEYBRIDGE,
    ENUMERATED,
    CDBS,
    COALS,
    ELS,
    IBFS,
    LICENSE,
    ULS,
    BDBS,
    COFETEL,
    PEERING;

    public String value() {
        return name();
    }

    public static EnumWsifDataSource fromValue(String v) {
        return valueOf(v);
    }

}
