//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.enumerated;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumRegistrar.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumRegistrar">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FCC"/>
 *     &lt;enumeration value="INDUSTRYCANADA"/>
 *     &lt;enumeration value="COFETEL"/>
 *     &lt;enumeration value="AIRITY"/>
 *     &lt;enumeration value="COMSEARCH"/>
 *     &lt;enumeration value="GOOGLE"/>
 *     &lt;enumeration value="KEYBRIDGE"/>
 *     &lt;enumeration value="LSTELCOM"/>
 *     &lt;enumeration value="MICROSOFT"/>
 *     &lt;enumeration value="RADIOSOFT"/>
 *     &lt;enumeration value="NEUSTAR"/>
 *     &lt;enumeration value="SPECTRUMBRIDGE"/>
 *     &lt;enumeration value="TELCORDIA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "enumRegistrar")
@XmlEnum
public enum EnumRegistrar {

    FCC,
    INDUSTRYCANADA,
    COFETEL,
    AIRITY,
    COMSEARCH,
    GOOGLE,
    KEYBRIDGE,
    LSTELCOM,
    MICROSOFT,
    RADIOSOFT,
    NEUSTAR,
    SPECTRUMBRIDGE,
    TELCORDIA;

    public String value() {
        return name();
    }

    public static EnumRegistrar fromValue(String v) {
        return valueOf(v);
    }

}
