//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.enumerated;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumWsifWsdMode.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumWsifWsdMode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PSEUDO"/>
 *     &lt;enumeration value="LPAUX"/>
 *     &lt;enumeration value="LPAUX_RESERVED"/>
 *     &lt;enumeration value="CLIENT"/>
 *     &lt;enumeration value="ACCESS_POINT"/>
 *     &lt;enumeration value="ACCESS_POINT_ADJACENT"/>
 *     &lt;enumeration value="ACCESS_POINT_MOBILE"/>
 *     &lt;enumeration value="ACCESS_POINT_FIXED"/>
 *     &lt;enumeration value="FORBIDDEN_WSD"/>
 *     &lt;enumeration value="FORBIDDEN_WSD_FIXED"/>
 *     &lt;enumeration value="FORBIDDEN_LPAUX"/>
 *     &lt;enumeration value="FORBIDDEN_BY_RULE"/>
 *     &lt;enumeration value="FORBIDDEN_BY_ENFORCEMENT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "enumWsifWsdMode")
@XmlEnum
public enum EnumWsifWsdMode {

    PSEUDO,
    LPAUX,
    LPAUX_RESERVED,
    CLIENT,
    ACCESS_POINT,
    ACCESS_POINT_ADJACENT,
    ACCESS_POINT_MOBILE,
    ACCESS_POINT_FIXED,
    FORBIDDEN_WSD,
    FORBIDDEN_WSD_FIXED,
    FORBIDDEN_LPAUX,
    FORBIDDEN_BY_RULE,
    FORBIDDEN_BY_ENFORCEMENT;

    public String value() {
        return name();
    }

    public static EnumWsifWsdMode fromValue(String v) {
        return valueOf(v);
    }

}
