//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.enumerated;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumWsifPathType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumWsifPathType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="P2P"/>
 *     &lt;enumeration value="P2MP"/>
 *     &lt;enumeration value="MP2P"/>
 *     &lt;enumeration value="MESH"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "enumWsifPathType")
@XmlEnum
public enum EnumWsifPathType {

    @XmlEnumValue("P2P")
    P_2_P("P2P"),
    @XmlEnumValue("P2MP")
    P_2_MP("P2MP"),
    @XmlEnumValue("MP2P")
    MP_2_P("MP2P"),
    MESH("MESH"),
    OTHER("OTHER");
    private final String value;

    EnumWsifPathType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumWsifPathType fromValue(String v) {
        for (EnumWsifPathType c: EnumWsifPathType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
