//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity.enumerated;

import com.keybridgeglobal.wsif.entity.Coordinate;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumRadioAstronomy complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="enumRadioAstronomy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="geometry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}coordinate" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="siteId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="observatory" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="latDeg" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="latMin" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="latSec" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="latDir" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="lonDeg" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="lonMin" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="lonSec" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="lonDir" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enumRadioAstronomy", propOrder = {
    "geometry",
    "coordinate"
})
public class EnumRadioAstronomy {

    @XmlElement(required = true)
    protected String geometry;
    protected Coordinate coordinate;
    @XmlAttribute(name = "siteId", required = true)
    protected String siteId;
    @XmlAttribute(name = "observatory", required = true)
    protected String observatory;
    @XmlAttribute(name = "latDeg", required = true)
    protected int latDeg;
    @XmlAttribute(name = "latMin", required = true)
    protected int latMin;
    @XmlAttribute(name = "latSec", required = true)
    protected double latSec;
    @XmlAttribute(name = "latDir", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int latDir;
    @XmlAttribute(name = "lonDeg", required = true)
    protected int lonDeg;
    @XmlAttribute(name = "lonMin", required = true)
    protected int lonMin;
    @XmlAttribute(name = "lonSec", required = true)
    protected double lonSec;
    @XmlAttribute(name = "lonDir", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int lonDir;

    /**
     * Gets the value of the geometry property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGeometry() {
        return geometry;
    }

    /**
     * Sets the value of the geometry property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGeometry(String value) {
        this.geometry = value;
    }

    /**
     * Gets the value of the coordinate property.
     *
     * @return
     *     possible object is
     *     {@link Coordinate }
     *
     */
    public Coordinate getCoordinate() {
        return coordinate;
    }

    /**
     * Sets the value of the coordinate property.
     *
     * @param value
     *     allowed object is
     *     {@link Coordinate }
     *
     */
    public void setCoordinate(Coordinate value) {
        this.coordinate = value;
    }

    /**
     * Gets the value of the siteId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * Sets the value of the siteId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSiteId(String value) {
        this.siteId = value;
    }

    /**
     * Gets the value of the observatory property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getObservatory() {
        return observatory;
    }

    /**
     * Sets the value of the observatory property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setObservatory(String value) {
        this.observatory = value;
    }

    /**
     * Gets the value of the latDeg property.
     *
     */
    public int getLatDeg() {
        return latDeg;
    }

    /**
     * Sets the value of the latDeg property.
     *
     */
    public void setLatDeg(int value) {
        this.latDeg = value;
    }

    /**
     * Gets the value of the latMin property.
     *
     */
    public int getLatMin() {
        return latMin;
    }

    /**
     * Sets the value of the latMin property.
     *
     */
    public void setLatMin(int value) {
        this.latMin = value;
    }

    /**
     * Gets the value of the latSec property.
     *
     */
    public double getLatSec() {
        return latSec;
    }

    /**
     * Sets the value of the latSec property.
     *
     */
    public void setLatSec(double value) {
        this.latSec = value;
    }

    /**
     * Gets the value of the latDir property.
     *
     */
    public int getLatDir() {
        return latDir;
    }

    /**
     * Sets the value of the latDir property.
     *
     */
    public void setLatDir(int value) {
        this.latDir = value;
    }

    /**
     * Gets the value of the lonDeg property.
     *
     */
    public int getLonDeg() {
        return lonDeg;
    }

    /**
     * Sets the value of the lonDeg property.
     *
     */
    public void setLonDeg(int value) {
        this.lonDeg = value;
    }

    /**
     * Gets the value of the lonMin property.
     *
     */
    public int getLonMin() {
        return lonMin;
    }

    /**
     * Sets the value of the lonMin property.
     *
     */
    public void setLonMin(int value) {
        this.lonMin = value;
    }

    /**
     * Gets the value of the lonSec property.
     *
     */
    public double getLonSec() {
        return lonSec;
    }

    /**
     * Sets the value of the lonSec property.
     *
     */
    public void setLonSec(double value) {
        this.lonSec = value;
    }

    /**
     * Gets the value of the lonDir property.
     *
     */
    public int getLonDir() {
        return lonDir;
    }

    /**
     * Sets the value of the lonDir property.
     *
     */
    public void setLonDir(int value) {
        this.lonDir = value;
    }

}
