//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity.enumerated;

import com.keybridgeglobal.wsif.entity.Channel;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumOffshoreRadio complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="enumOffshoreRadio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}channel"/>
 *         &lt;element name="geometry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ruleNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enumOffshoreRadio", propOrder = {
    "channel",
    "geometry"
})
public class EnumOffshoreRadio {

    @XmlElement(required = true)
    protected Channel channel;
    @XmlElement(required = true)
    protected String geometry;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "ruleNum")
    protected String ruleNum;

    /**
     * Gets the value of the channel property.
     *
     * @return
     *     possible object is
     *     {@link Channel }
     *
     */
    public Channel getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     *
     * @param value
     *     allowed object is
     *     {@link Channel }
     *
     */
    public void setChannel(Channel value) {
        this.channel = value;
    }

    /**
     * Gets the value of the geometry property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGeometry() {
        return geometry;
    }

    /**
     * Sets the value of the geometry property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGeometry(String value) {
        this.geometry = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the ruleNum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRuleNum() {
        return ruleNum;
    }

    /**
     * Sets the value of the ruleNum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRuleNum(String value) {
        this.ruleNum = value;
    }

}
