//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contact complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="contact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}address" minOccurs="0"/>
 *         &lt;element name="vCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="email" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nameFirst" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nameLast" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="organization" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="phone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fax" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cell" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contactType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contact", propOrder = {
    "address",
    "vCard"
})
public class Contact {

    protected Address address;
    protected String vCard;
    @XmlAttribute(name = "email", required = true)
    protected String email;
    @XmlAttribute(name = "nameFirst")
    protected String nameFirst;
    @XmlAttribute(name = "nameLast")
    protected String nameLast;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "organization")
    protected String organization;
    @XmlAttribute(name = "phone")
    protected String phone;
    @XmlAttribute(name = "fax")
    protected String fax;
    @XmlAttribute(name = "cell")
    protected String cell;
    @XmlAttribute(name = "contactType")
    protected String contactType;

    /**
     * Gets the value of the address property.
     *
     * @return
     *     possible object is
     *     {@link Address }
     *
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value
     *     allowed object is
     *     {@link Address }
     *
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the vCard property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVCard() {
        return vCard;
    }

    /**
     * Sets the value of the vCard property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVCard(String value) {
        this.vCard = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the nameFirst property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNameFirst() {
        return nameFirst;
    }

    /**
     * Sets the value of the nameFirst property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNameFirst(String value) {
        this.nameFirst = value;
    }

    /**
     * Gets the value of the nameLast property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNameLast() {
        return nameLast;
    }

    /**
     * Sets the value of the nameLast property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNameLast(String value) {
        this.nameLast = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the organization property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrganization(String value) {
        this.organization = value;
    }

    /**
     * Gets the value of the phone property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the fax property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the cell property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCell() {
        return cell;
    }

    /**
     * Sets the value of the cell property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCell(String value) {
        this.cell = value;
    }

    /**
     * Gets the value of the contactType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getContactType() {
        return contactType;
    }

    /**
     * Sets the value of the contactType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setContactType(String value) {
        this.contactType = value;
    }

}
