//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity;

import com.keybridgeglobal.wsif.enumerated.EnumWsifDatum;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for coordinate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="coordinate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="latitude" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="accuracy" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="altitude" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="altitudeAccuracy" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="heading" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="speed" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="domTimeStamp" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="datum" use="required" type="{}enumWsifDatum" />
 *       &lt;attribute name="elevationModel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="averageTerrain" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coordinate")
public class Coordinate {

    @XmlAttribute(name = "latitude", required = true)
    protected double latitude;
    @XmlAttribute(name = "longitude", required = true)
    protected double longitude;
    @XmlAttribute(name = "accuracy")
    protected Double accuracy;
    @XmlAttribute(name = "altitude")
    protected Double altitude;
    @XmlAttribute(name = "altitudeAccuracy")
    protected Double altitudeAccuracy;
    @XmlAttribute(name = "heading")
    protected Double heading;
    @XmlAttribute(name = "speed")
    protected Double speed;
    @XmlAttribute(name = "domTimeStamp")
    protected Long domTimeStamp;
    @XmlAttribute(name = "datum", required = true)
    protected EnumWsifDatum datum;
    @XmlAttribute(name = "elevationModel")
    protected String elevationModel;
    @XmlAttribute(name = "averageTerrain")
    protected Double averageTerrain;

    /**
     * Gets the value of the latitude property.
     *
     */
    public double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     *
     */
    public void setLatitude(double value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     *
     */
    public double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     *
     */
    public void setLongitude(double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the accuracy property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getAccuracy() {
        return accuracy;
    }

    /**
     * Sets the value of the accuracy property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setAccuracy(Double value) {
        this.accuracy = value;
    }

    /**
     * Gets the value of the altitude property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getAltitude() {
        return altitude;
    }

    /**
     * Sets the value of the altitude property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setAltitude(Double value) {
        this.altitude = value;
    }

    /**
     * Gets the value of the altitudeAccuracy property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getAltitudeAccuracy() {
        return altitudeAccuracy;
    }

    /**
     * Sets the value of the altitudeAccuracy property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setAltitudeAccuracy(Double value) {
        this.altitudeAccuracy = value;
    }

    /**
     * Gets the value of the heading property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setHeading(Double value) {
        this.heading = value;
    }

    /**
     * Gets the value of the speed property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setSpeed(Double value) {
        this.speed = value;
    }

    /**
     * Gets the value of the domTimeStamp property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getDomTimeStamp() {
        return domTimeStamp;
    }

    /**
     * Sets the value of the domTimeStamp property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setDomTimeStamp(Long value) {
        this.domTimeStamp = value;
    }

    /**
     * Gets the value of the datum property.
     *
     * @return
     *     possible object is
     *     {@link EnumWsifDatum }
     *
     */
    public EnumWsifDatum getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     *
     * @param value
     *     allowed object is
     *     {@link EnumWsifDatum }
     *
     */
    public void setDatum(EnumWsifDatum value) {
        this.datum = value;
    }

    /**
     * Gets the value of the elevationModel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getElevationModel() {
        return elevationModel;
    }

    /**
     * Sets the value of the elevationModel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setElevationModel(String value) {
        this.elevationModel = value;
    }

    /**
     * Gets the value of the averageTerrain property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getAverageTerrain() {
        return averageTerrain;
    }

    /**
     * Sets the value of the averageTerrain property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setAverageTerrain(Double value) {
        this.averageTerrain = value;
    }

}
