//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity;

import com.keybridgeglobal.wsif.enumerated.EnumWsifWirelessServiceType;
import com.keybridgeglobal.wsif.entity.device.RxGeneric;
import com.keybridgeglobal.wsif.entity.device.RxLpaux;
import com.keybridgeglobal.wsif.entity.device.RxMicrowave;
import com.keybridgeglobal.wsif.entity.device.RxTv;
import com.keybridgeglobal.wsif.entity.device.TxGeneric;
import com.keybridgeglobal.wsif.entity.device.TxLpaux;
import com.keybridgeglobal.wsif.entity.device.TxMicrowave;
import com.keybridgeglobal.wsif.entity.device.TxRxLandMobile;
import com.keybridgeglobal.wsif.entity.device.TxRxLandMobileBase;
import com.keybridgeglobal.wsif.entity.device.TxRxWsd;
import com.keybridgeglobal.wsif.entity.device.TxTv;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for device complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="device">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}antenna"/>
 *       &lt;/sequence>
 *       &lt;attribute name="frequency" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="chWidth" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="erp" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="erpMax" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="digital" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="passive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="deviceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="deviceSn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="digitalModRate" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="digitalModType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="equipmentClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ea" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="equipmentRuleNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="emissionCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wirelessServiceType" type="{}enumWsifWirelessServiceType" />
 *       &lt;attribute name="antennaRotation" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="antennaHag" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="antennaHaat" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="antennaRcAmsl" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "device", propOrder = {
    "antenna"
})
@XmlSeeAlso({
    RxLpaux.class,
    TxRxLandMobileBase.class,
    RxTv.class,
    RxGeneric.class,
    TxGeneric.class,
    TxMicrowave.class,
    TxLpaux.class,
    RxMicrowave.class,
    TxTv.class,
    TxRxWsd.class,
    TxRxLandMobile.class
})
public abstract class Device {

    @XmlElement(required = true)
    protected Antenna antenna;
    @XmlAttribute(name = "frequency")
    protected Double frequency;
    @XmlAttribute(name = "chWidth")
    protected Double chWidth;
    @XmlAttribute(name = "erp")
    protected Double erp;
    @XmlAttribute(name = "erpMax")
    protected Double erpMax;
    @XmlAttribute(name = "digital", required = true)
    protected boolean digital;
    @XmlAttribute(name = "passive", required = true)
    protected boolean passive;
    @XmlAttribute(name = "deviceId")
    protected String deviceId;
    @XmlAttribute(name = "deviceSn")
    protected String deviceSn;
    @XmlAttribute(name = "manufacturer")
    protected String manufacturer;
    @XmlAttribute(name = "model")
    protected String model;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "digitalModRate")
    protected Double digitalModRate;
    @XmlAttribute(name = "digitalModType")
    protected String digitalModType;
    @XmlAttribute(name = "equipmentClass")
    protected String equipmentClass;
    @XmlAttribute(name = "ea")
    protected String ea;
    @XmlAttribute(name = "equipmentRuleNum")
    protected String equipmentRuleNum;
    @XmlAttribute(name = "emissionCode")
    protected String emissionCode;
    @XmlAttribute(name = "wirelessServiceType")
    protected EnumWsifWirelessServiceType wirelessServiceType;
    @XmlAttribute(name = "antennaRotation")
    protected Double antennaRotation;
    @XmlAttribute(name = "antennaHag", required = true)
    protected double antennaHag;
    @XmlAttribute(name = "antennaHaat")
    protected Double antennaHaat;
    @XmlAttribute(name = "antennaRcAmsl")
    protected Double antennaRcAmsl;

    /**
     * Gets the value of the antenna property.
     *
     * @return
     *     possible object is
     *     {@link Antenna }
     *
     */
    public Antenna getAntenna() {
        return antenna;
    }

    /**
     * Sets the value of the antenna property.
     *
     * @param value
     *     allowed object is
     *     {@link Antenna }
     *
     */
    public void setAntenna(Antenna value) {
        this.antenna = value;
    }

    /**
     * Gets the value of the frequency property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setFrequency(Double value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the chWidth property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getChWidth() {
        return chWidth;
    }

    /**
     * Sets the value of the chWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setChWidth(Double value) {
        this.chWidth = value;
    }

    /**
     * Gets the value of the erp property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getErp() {
        return erp;
    }

    /**
     * Sets the value of the erp property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setErp(Double value) {
        this.erp = value;
    }

    /**
     * Gets the value of the erpMax property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getErpMax() {
        return erpMax;
    }

    /**
     * Sets the value of the erpMax property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setErpMax(Double value) {
        this.erpMax = value;
    }

    /**
     * Gets the value of the digital property.
     *
     */
    public boolean isDigital() {
        return digital;
    }

    /**
     * Sets the value of the digital property.
     *
     */
    public void setDigital(boolean value) {
        this.digital = value;
    }

    /**
     * Gets the value of the passive property.
     *
     */
    public boolean isPassive() {
        return passive;
    }

    /**
     * Sets the value of the passive property.
     *
     */
    public void setPassive(boolean value) {
        this.passive = value;
    }

    /**
     * Gets the value of the deviceId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Sets the value of the deviceId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDeviceId(String value) {
        this.deviceId = value;
    }

    /**
     * Gets the value of the deviceSn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDeviceSn() {
        return deviceSn;
    }

    /**
     * Sets the value of the deviceSn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDeviceSn(String value) {
        this.deviceSn = value;
    }

    /**
     * Gets the value of the manufacturer property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the model property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the digitalModRate property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getDigitalModRate() {
        return digitalModRate;
    }

    /**
     * Sets the value of the digitalModRate property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setDigitalModRate(Double value) {
        this.digitalModRate = value;
    }

    /**
     * Gets the value of the digitalModType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDigitalModType() {
        return digitalModType;
    }

    /**
     * Sets the value of the digitalModType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDigitalModType(String value) {
        this.digitalModType = value;
    }

    /**
     * Gets the value of the equipmentClass property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEquipmentClass() {
        return equipmentClass;
    }

    /**
     * Sets the value of the equipmentClass property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEquipmentClass(String value) {
        this.equipmentClass = value;
    }

    /**
     * Gets the value of the ea property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEa() {
        return ea;
    }

    /**
     * Sets the value of the ea property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEa(String value) {
        this.ea = value;
    }

    /**
     * Gets the value of the equipmentRuleNum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEquipmentRuleNum() {
        return equipmentRuleNum;
    }

    /**
     * Sets the value of the equipmentRuleNum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEquipmentRuleNum(String value) {
        this.equipmentRuleNum = value;
    }

    /**
     * Gets the value of the emissionCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEmissionCode() {
        return emissionCode;
    }

    /**
     * Sets the value of the emissionCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEmissionCode(String value) {
        this.emissionCode = value;
    }

    /**
     * Gets the value of the wirelessServiceType property.
     *
     * @return
     *     possible object is
     *     {@link EnumWsifWirelessServiceType }
     *
     */
    public EnumWsifWirelessServiceType getWirelessServiceType() {
        return wirelessServiceType;
    }

    /**
     * Sets the value of the wirelessServiceType property.
     *
     * @param value
     *     allowed object is
     *     {@link EnumWsifWirelessServiceType }
     *
     */
    public void setWirelessServiceType(EnumWsifWirelessServiceType value) {
        this.wirelessServiceType = value;
    }

    /**
     * Gets the value of the antennaRotation property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getAntennaRotation() {
        return antennaRotation;
    }

    /**
     * Sets the value of the antennaRotation property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setAntennaRotation(Double value) {
        this.antennaRotation = value;
    }

    /**
     * Gets the value of the antennaHag property.
     *
     */
    public double getAntennaHag() {
        return antennaHag;
    }

    /**
     * Sets the value of the antennaHag property.
     *
     */
    public void setAntennaHag(double value) {
        this.antennaHag = value;
    }

    /**
     * Gets the value of the antennaHaat property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getAntennaHaat() {
        return antennaHaat;
    }

    /**
     * Sets the value of the antennaHaat property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setAntennaHaat(Double value) {
        this.antennaHaat = value;
    }

    /**
     * Gets the value of the antennaRcAmsl property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getAntennaRcAmsl() {
        return antennaRcAmsl;
    }

    /**
     * Sets the value of the antennaRcAmsl property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setAntennaRcAmsl(Double value) {
        this.antennaRcAmsl = value;
    }

}
