//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for geometry complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="geometry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="envelope" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="geometry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="polygon" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "geometry", propOrder = {
    "envelope",
    "geometry",
    "polygon"
})
public class Geometry {

    @XmlElement(required = true)
    protected String envelope;
    @XmlElement(required = true)
    protected String geometry;
    @XmlElement(required = true)
    protected String polygon;

    /**
     * Gets the value of the envelope property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEnvelope() {
        return envelope;
    }

    /**
     * Sets the value of the envelope property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEnvelope(String value) {
        this.envelope = value;
    }

    /**
     * Gets the value of the geometry property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGeometry() {
        return geometry;
    }

    /**
     * Sets the value of the geometry property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGeometry(String value) {
        this.geometry = value;
    }

    /**
     * Gets the value of the polygon property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPolygon() {
        return polygon;
    }

    /**
     * Sets the value of the polygon property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPolygon(String value) {
        this.polygon = value;
    }

}
