//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity;

import com.keybridgeglobal.wsif.enumerated.EnumWsifScheduleClassification;
import com.keybridgeglobal.wsif.enumerated.EnumWsifScheduleTransparency;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for schedule complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="schedule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vevent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dtstart" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="dtend" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="rrule" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timeZone" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="categories" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="created" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="classification" type="{}enumWsifScheduleClassification" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="organizer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transparency" type="{}enumWsifScheduleTransparency" />
 *       &lt;attribute name="allDayEvent" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="dateExpiration" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "schedule", propOrder = {
    "vevent"
})
public class Schedule {

    protected String vevent;
    @XmlAttribute(name = "dtstart", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtstart;
    @XmlAttribute(name = "dtend", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtend;
    @XmlAttribute(name = "rrule", required = true)
    protected String rrule;
    @XmlAttribute(name = "timeZone", required = true)
    protected String timeZone;
    @XmlAttribute(name = "uid", required = true)
    protected String uid;
    @XmlAttribute(name = "categories")
    protected String categories;
    @XmlAttribute(name = "created", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar created;
    @XmlAttribute(name = "classification")
    protected EnumWsifScheduleClassification classification;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "organizer")
    protected String organizer;
    @XmlAttribute(name = "priority")
    protected Integer priority;
    @XmlAttribute(name = "summary")
    protected String summary;
    @XmlAttribute(name = "transparency")
    protected EnumWsifScheduleTransparency transparency;
    @XmlAttribute(name = "allDayEvent", required = true)
    protected boolean allDayEvent;
    @XmlAttribute(name = "dateExpiration")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateExpiration;

    /**
     * Gets the value of the vevent property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVevent() {
        return vevent;
    }

    /**
     * Sets the value of the vevent property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVevent(String value) {
        this.vevent = value;
    }

    /**
     * Gets the value of the dtstart property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDtstart() {
        return dtstart;
    }

    /**
     * Sets the value of the dtstart property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDtstart(XMLGregorianCalendar value) {
        this.dtstart = value;
    }

    /**
     * Gets the value of the dtend property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDtend() {
        return dtend;
    }

    /**
     * Sets the value of the dtend property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDtend(XMLGregorianCalendar value) {
        this.dtend = value;
    }

    /**
     * Gets the value of the rrule property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRrule() {
        return rrule;
    }

    /**
     * Sets the value of the rrule property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRrule(String value) {
        this.rrule = value;
    }

    /**
     * Gets the value of the timeZone property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the uid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the categories property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCategories(String value) {
        this.categories = value;
    }

    /**
     * Gets the value of the created property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setCreated(XMLGregorianCalendar value) {
        this.created = value;
    }

    /**
     * Gets the value of the classification property.
     *
     * @return
     *     possible object is
     *     {@link EnumWsifScheduleClassification }
     *
     */
    public EnumWsifScheduleClassification getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     *
     * @param value
     *     allowed object is
     *     {@link EnumWsifScheduleClassification }
     *
     */
    public void setClassification(EnumWsifScheduleClassification value) {
        this.classification = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the organizer property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrganizer() {
        return organizer;
    }

    /**
     * Sets the value of the organizer property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrganizer(String value) {
        this.organizer = value;
    }

    /**
     * Gets the value of the priority property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the summary property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSummary(String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the transparency property.
     *
     * @return
     *     possible object is
     *     {@link EnumWsifScheduleTransparency }
     *
     */
    public EnumWsifScheduleTransparency getTransparency() {
        return transparency;
    }

    /**
     * Sets the value of the transparency property.
     *
     * @param value
     *     allowed object is
     *     {@link EnumWsifScheduleTransparency }
     *
     */
    public void setTransparency(EnumWsifScheduleTransparency value) {
        this.transparency = value;
    }

    /**
     * Gets the value of the allDayEvent property.
     *
     */
    public boolean isAllDayEvent() {
        return allDayEvent;
    }

    /**
     * Sets the value of the allDayEvent property.
     *
     */
    public void setAllDayEvent(boolean value) {
        this.allDayEvent = value;
    }

    /**
     * Gets the value of the dateExpiration property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateExpiration() {
        return dateExpiration;
    }

    /**
     * Sets the value of the dateExpiration property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateExpiration(XMLGregorianCalendar value) {
        this.dateExpiration = value;
    }

}
