//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity.device;

import com.keybridgeglobal.wsif.entity.Device;
import com.keybridgeglobal.wsif.entity.Channel;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txLpaux complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="txLpaux">
 *   &lt;complexContent>
 *     &lt;extension base="{}device">
 *       &lt;sequence>
 *         &lt;element ref="{}channel"/>
 *         &lt;element name="receiver" type="{}rxLpaux" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="deviceType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="groupId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subGroupId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "txLpaux", propOrder = {
    "channel",
    "receiver"
})
public class TxLpaux
    extends Device
{

    @XmlElement(required = true)
    protected Channel channel;
    protected RxLpaux receiver;
    @XmlAttribute(name = "deviceType")
    protected String deviceType;
    @XmlAttribute(name = "groupId")
    protected String groupId;
    @XmlAttribute(name = "subGroupId")
    protected String subGroupId;

    /**
     * Gets the value of the channel property.
     *
     * @return
     *     possible object is
     *     {@link Channel }
     *
     */
    public Channel getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     *
     * @param value
     *     allowed object is
     *     {@link Channel }
     *
     */
    public void setChannel(Channel value) {
        this.channel = value;
    }

    /**
     * Gets the value of the receiver property.
     *
     * @return
     *     possible object is
     *     {@link RxLpaux }
     *
     */
    public RxLpaux getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     *
     * @param value
     *     allowed object is
     *     {@link RxLpaux }
     *
     */
    public void setReceiver(RxLpaux value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the deviceType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Sets the value of the deviceType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDeviceType(String value) {
        this.deviceType = value;
    }

    /**
     * Gets the value of the groupId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the subGroupId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubGroupId() {
        return subGroupId;
    }

    /**
     * Sets the value of the subGroupId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubGroupId(String value) {
        this.subGroupId = value;
    }

}
