//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity.device;

import com.keybridgeglobal.wsif.entity.Device;
import com.keybridgeglobal.wsif.entity.Channel;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txMicrowave complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="txMicrowave">
 *   &lt;complexContent>
 *     &lt;extension base="{}device">
 *       &lt;sequence>
 *         &lt;element name="channelList" type="{}channel" maxOccurs="unbounded"/>
 *         &lt;element name="receiver" type="{}rxMicrowave" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="broadcastCallSign" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pathTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "txMicrowave", propOrder = {
    "channelList",
    "receiver"
})
public class TxMicrowave
    extends Device
{

    @XmlElement(required = true)
    protected List<Channel> channelList;
    protected RxMicrowave receiver;
    @XmlAttribute(name = "broadcastCallSign")
    protected String broadcastCallSign;
    @XmlAttribute(name = "pathTypeDescription")
    protected String pathTypeDescription;

    /**
     * Gets the value of the channelList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channelList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannelList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Channel }
     *
     *
     */
    public List<Channel> getChannelList() {
        if (channelList == null) {
            channelList = new ArrayList<Channel>();
        }
        return this.channelList;
    }

    /**
     * Gets the value of the receiver property.
     *
     * @return
     *     possible object is
     *     {@link RxMicrowave }
     *
     */
    public RxMicrowave getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     *
     * @param value
     *     allowed object is
     *     {@link RxMicrowave }
     *
     */
    public void setReceiver(RxMicrowave value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the broadcastCallSign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBroadcastCallSign() {
        return broadcastCallSign;
    }

    /**
     * Sets the value of the broadcastCallSign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBroadcastCallSign(String value) {
        this.broadcastCallSign = value;
    }

    /**
     * Gets the value of the pathTypeDescription property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPathTypeDescription() {
        return pathTypeDescription;
    }

    /**
     * Sets the value of the pathTypeDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPathTypeDescription(String value) {
        this.pathTypeDescription = value;
    }

}
