//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity.device;

import com.keybridgeglobal.wsif.entity.Device;
import com.keybridgeglobal.wsif.entity.Channel;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txRxLandMobileBase complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="txRxLandMobileBase">
 *   &lt;complexContent>
 *     &lt;extension base="{}device">
 *       &lt;sequence>
 *         &lt;element name="channelList" type="{}channel" maxOccurs="unbounded"/>
 *         &lt;element name="mobileUnitList" type="{}txRxLandMobile" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="radiusOfOperation" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "txRxLandMobileBase", propOrder = {
    "channelList",
    "mobileUnitList"
})
public class TxRxLandMobileBase
    extends Device
{

    @XmlElement(required = true)
    protected List<Channel> channelList;
    protected List<TxRxLandMobile> mobileUnitList;
    @XmlAttribute(name = "radiusOfOperation")
    protected Long radiusOfOperation;

    /**
     * Gets the value of the channelList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channelList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannelList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Channel }
     *
     *
     */
    public List<Channel> getChannelList() {
        if (channelList == null) {
            channelList = new ArrayList<Channel>();
        }
        return this.channelList;
    }

    /**
     * Gets the value of the mobileUnitList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mobileUnitList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMobileUnitList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TxRxLandMobile }
     *
     *
     */
    public List<TxRxLandMobile> getMobileUnitList() {
        if (mobileUnitList == null) {
            mobileUnitList = new ArrayList<TxRxLandMobile>();
        }
        return this.mobileUnitList;
    }

    /**
     * Gets the value of the radiusOfOperation property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getRadiusOfOperation() {
        return radiusOfOperation;
    }

    /**
     * Sets the value of the radiusOfOperation property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setRadiusOfOperation(Long value) {
        this.radiusOfOperation = value;
    }

}
