//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:55:13 PM EDT
//


package com.keybridgeglobal.wsif.entity.device;

import com.keybridgeglobal.wsif.entity.Device;
import com.keybridgeglobal.wsif.entity.Channel;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txTv complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="txTv">
 *   &lt;complexContent>
 *     &lt;extension base="{}device">
 *       &lt;sequence>
 *         &lt;element ref="{}channel"/>
 *         &lt;element name="receivers" type="{}rxTv" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="broadcastCallSign" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="networkAffiliation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "txTv", propOrder = {
    "channel",
    "receivers"
})
public class TxTv
    extends Device
{

    @XmlElement(required = true)
    protected Channel channel;
    protected List<RxTv> receivers;
    @XmlAttribute(name = "broadcastCallSign")
    protected String broadcastCallSign;
    @XmlAttribute(name = "networkAffiliation")
    protected String networkAffiliation;

    /**
     * Gets the value of the channel property.
     *
     * @return
     *     possible object is
     *     {@link Channel }
     *
     */
    public Channel getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     *
     * @param value
     *     allowed object is
     *     {@link Channel }
     *
     */
    public void setChannel(Channel value) {
        this.channel = value;
    }

    /**
     * Gets the value of the receivers property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the receivers property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReceivers().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RxTv }
     *
     *
     */
    public List<RxTv> getReceivers() {
        if (receivers == null) {
            receivers = new ArrayList<RxTv>();
        }
        return this.receivers;
    }

    /**
     * Gets the value of the broadcastCallSign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBroadcastCallSign() {
        return broadcastCallSign;
    }

    /**
     * Sets the value of the broadcastCallSign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBroadcastCallSign(String value) {
        this.broadcastCallSign = value;
    }

    /**
     * Gets the value of the networkAffiliation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNetworkAffiliation() {
        return networkAffiliation;
    }

    /**
     * Sets the value of the networkAffiliation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNetworkAffiliation(String value) {
        this.networkAffiliation = value;
    }

}
